user www-data;

events
{
	worker_connections 1024;
}

http 
{
	include /etc/nginx/mime.types;

	server
	{
		listen 80;
		listen [::]:80;
		server_name ${INCEPTION_DOMAIN};
		return 301 https://$host$request_uri;
	}

	server
	{
		listen ${INCEPTION_NGINX_PORT} ssl;
		listen [::]:${INCEPTION_NGINX_PORT} ssl;
		server_name ${INCEPTION_DOMAIN};
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/ssl/public_certificate.crt;
		ssl_certificate_key /etc/nginx/ssl/private.key;
		root /var/www/html;
		index index.php index.html;
		location ~ \.php$
		{
			include fastcgi_params;
			fastcgi_pass wordpress:${INCEPTION_WP_PORT};
			fastcgi_index index.php;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
		}
	}
}
